In [11]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist, squareform
import matplotlib.pyplot as plt

df = pd.read_csv('Walt_disney_movie_dataset.csv')


In [8]:
running_time = df["Running time (int)"]
box_office = df["Box office (float)"]
budget = df["Budget (float)"]
data_subset = pd.concat([running_time, box_office, budget],axis=1)
# data_subset = [budget, box_office, running_time]
type(data_subset)
data_subset

Running time (int)  Box office (float)  Budget (float)
0                  41.0        4.547200e+01             NaN
1                  83.0        4.180000e+08       1490000.0
2                  88.0        1.640000e+08       2600000.0
3                 126.0        8.330000e+07       2280000.0
4                  74.0        9.600000e+05        600000.0
..                  ...                 ...             ...
447                 NaN                 NaN             NaN
448                96.0        4.490000e+07      28000000.0
449                 NaN                 NaN             NaN
450                 NaN                 NaN             NaN
451                 NaN                 NaN             NaN

[452 rows x 3 columns]

In [35]:
dis_vector = pdist(data_subset, metric='matching')
dis_matrix = squareform(dis_vector,force='tomatrix')
print(dis_matrix)
x = dis_matrix.shape
x = x[0]
count =0
for i in range(0,x):
    for j in range(0,x):
        if dis_matrix[i][j]!=0 and dis_matrix[i][j]!=1:
            print("row: ",i," col: ",j, "value: ",dis_matrix[i][j])
            count+=1
print(count/2)

[[0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 1. 0.]]
row:  1  col:  36 value:  0.6666666666666666
row:  1  col:  37 value:  0.6666666666666666
row:  1  col:  111 value:  0.6666666666666666
row:  1  col:  150 value:  0.6666666666666666
row:  1  col:  169 value:  0.6666666666666666
row:  1  col:  230 value:  0.6666666666666666
row:  1  col:  231 value:  0.6666666666666666
row:  1  col:  244 value:  0.6666666666666666
row:  1  col:  311 value:  0.6666666666666666
row:  2  col:  104 value:  0.6666666666666666
row:  2  col:  113 value:  0.6666666666666666
row:  2  col:  139 value:  0.6666666666666666
row:  2  col:  174 value:  0.6666666666666666
row:  2  col:  192 value:  0.6666666666666666
row:  2  col:  232 value:  0.6666666666666666
row:  2  col:  253 value:  0.6666666666666666
row:  2  col:  331 value:  0.6666666666666666
row:  2  col:  347 value:  0.6666666666666666
row:  4  col:  16 